name: test
on: 
  pull_request:
jobs:
  clone:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push to GitHub
      run: |
        ls -al
        cd Packages
        pip install pytest
        python3 -m pytest testing.py
