name: test
on: push
jobs:
  clone:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push to GitHub
      run: |
        git push -u origin master
        python testing.py
